In [2]:
import nltk
import pandas as pd
import numpy as np
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

In [3]:
corpus = 'When we were in Paris we  visited a lot of museums. We first went to the Louvre, the largest art museum in the world. I have always been interested in art so I spent many hours there. The museum is enourmous, so a week there would not be enough.'
corpus = "Moscow is the capital and largest city of Russia, standing on the Moskva River in Central Russia. It has a population estimated at over 13 million residents within the city limits, over 19.1 million residents in the urban area, and over 21.5 million residents in its metropolitan area. The city covers an area of 2,511 square kilometers (970 sq mi), while the urban area covers 5,891 square kilometers (2,275 sq mi), and the metropolitan area covers over 26,000 square kilometers (10,000 sq mi). Moscow is among the world's largest cities, being the most populous city entirely in Europe, the largest urban and metropolitan area in Europe, and the largest city by land area on the European continent.First documented in 1147, Moscow became the capital of the Grand Principality of Moscow, which led the unification of the Russian lands in the 15th century and became the center of a unified state. Following the proclamation of the Tsardom of Russia in 1547, Moscow remained the political and economic center for most of its history. During the reign of Peter the Great, the Russian capital was moved to the newly founded city of Saint Petersburg in 1712, leading to a decline in Moscow's importance throughout the imperial period. Following the Russian Revolution and the establishment of the Russian SFSR, the capital was moved back to Moscow in 1918. The city later became the political center of the Soviet Union and experienced significant population growth throughout the Soviet period. In the aftermath of the dissolution of the Soviet Union, Moscow remained the capital city of the newly reconstituted Russian Federation and has experienced continued growth.The northernmost and coldest megacity in the world, Moscow is governed as a federal city, where it serves as the political, economic, cultural, and scientific center of Russia and Eastern Europe. Moscow has one of the world's largest urban economies. Moscow has the second-highest number of billionaires of any city (tied with Hong Kong). The Moscow International Business Center is one of the largest financial centers in the world and features the majority of Europes tallest skyscrapers. Moscow was the host city of the 1980 Summer Olympics and one of the host cities of the 2018 FIFA World Cup."


In [4]:
#corpus = 'When we were in Paris we  visited a lot of museums. We first went to the Louvre, the largest art museum in the world. I have always been interested in art so I spent many hours there. The museum is enourmous, so a week there would not be enough.'

nltk.download('punkt')
nltk.download('punkt_tab')
 
# и применяем функцию к тексту
sentences = sent_tokenize(corpus)
sentences

[nltk_data] Downloading package punkt to /Users/apple/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/apple/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


['Moscow is the capital and largest city of Russia, standing on the Moskva River in Central Russia.',
 'It has a population estimated at over 13 million residents within the city limits, over 19.1 million residents in the urban area, and over 21.5 million residents in its metropolitan area.',
 'The city covers an area of 2,511 square kilometers (970 sq mi), while the urban area covers 5,891 square kilometers (2,275 sq mi), and the metropolitan area covers over 26,000 square kilometers (10,000 sq mi).',
 "Moscow is among the world's largest cities, being the most populous city entirely in Europe, the largest urban and metropolitan area in Europe, and the largest city by land area on the European continent.First documented in 1147, Moscow became the capital of the Grand Principality of Moscow, which led the unification of the Russian lands in the 15th century and became the center of a unified state.",
 'Following the proclamation of the Tsardom of Russia in 1547, Moscow remained the pol

In [5]:
# для этого создадим пустой список
tokens = []
 
# в цикле for пройдемся по каждому предложению
for sentence in sentences:
 
    # создадим списки из токенов
    t = word_tokenize(sentence)
 
    # и присоединим списки друг к другу
    tokens.extend(t)
 
print(tokens)



['Moscow', 'is', 'the', 'capital', 'and', 'largest', 'city', 'of', 'Russia', ',', 'standing', 'on', 'the', 'Moskva', 'River', 'in', 'Central', 'Russia', '.', 'It', 'has', 'a', 'population', 'estimated', 'at', 'over', '13', 'million', 'residents', 'within', 'the', 'city', 'limits', ',', 'over', '19.1', 'million', 'residents', 'in', 'the', 'urban', 'area', ',', 'and', 'over', '21.5', 'million', 'residents', 'in', 'its', 'metropolitan', 'area', '.', 'The', 'city', 'covers', 'an', 'area', 'of', '2,511', 'square', 'kilometers', '(', '970', 'sq', 'mi', ')', ',', 'while', 'the', 'urban', 'area', 'covers', '5,891', 'square', 'kilometers', '(', '2,275', 'sq', 'mi', ')', ',', 'and', 'the', 'metropolitan', 'area', 'covers', 'over', '26,000', 'square', 'kilometers', '(', '10,000', 'sq', 'mi', ')', '.', 'Moscow', 'is', 'among', 'the', 'world', "'s", 'largest', 'cities', ',', 'being', 'the', 'most', 'populous', 'city', 'entirely', 'in', 'Europe', ',', 'the', 'largest', 'urban', 'and', 'metropolitan'

In [6]:
# импортируем модуль стоп-слов
from nltk.corpus import stopwords
 
# скачаем словарь стоп-слов
nltk.download('stopwords')
 
# мы используем set, чтобы оставить только уникальные значения
unique_stops = set(stopwords.words('english'))
 
# создаём пустой список без стоп-слов
no_stops = []
 
# проходимся по всем токенам
for token in tokens:
 
    # переводим все слова в нижний регистр
    token = token.lower()
 
    # если токен не в списке стоп-слов и не является знаком пунктуации,
    if token not in unique_stops and token.isalpha():
 
        # добавляем его в список
        no_stops.append(token)
 
print(no_stops)

['moscow', 'capital', 'largest', 'city', 'russia', 'standing', 'moskva', 'river', 'central', 'russia', 'population', 'estimated', 'million', 'residents', 'within', 'city', 'limits', 'million', 'residents', 'urban', 'area', 'million', 'residents', 'metropolitan', 'area', 'city', 'covers', 'area', 'square', 'kilometers', 'sq', 'mi', 'urban', 'area', 'covers', 'square', 'kilometers', 'sq', 'mi', 'metropolitan', 'area', 'covers', 'square', 'kilometers', 'sq', 'mi', 'moscow', 'among', 'world', 'largest', 'cities', 'populous', 'city', 'entirely', 'europe', 'largest', 'urban', 'metropolitan', 'area', 'europe', 'largest', 'city', 'land', 'area', 'european', 'documented', 'moscow', 'became', 'capital', 'grand', 'principality', 'moscow', 'led', 'unification', 'russian', 'lands', 'century', 'became', 'center', 'unified', 'state', 'following', 'proclamation', 'tsardom', 'russia', 'moscow', 'remained', 'political', 'economic', 'center', 'history', 'reign', 'peter', 'great', 'russian', 'capital', 'm

[nltk_data] Downloading package stopwords to /Users/apple/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
# импортируем класс для лемматизации
from nltk.stem import WordNetLemmatizer
 
# импортируем словарь
nltk.download('wordnet')
 
# создаём объект этого класса
lemmatizer = WordNetLemmatizer()
 
# и пустой список для слов после лемматизации
lemmatized = []
 
# проходимся по всем токенам
for token in no_stops:
 
    # применяем лемматизацию
    token = lemmatizer.lemmatize(token)
 
    # добавляем слово после лемматизации в список
    lemmatized.append(token)
    
print(lemmatized)

[nltk_data] Downloading package wordnet to /Users/apple/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


['moscow', 'capital', 'largest', 'city', 'russia', 'standing', 'moskva', 'river', 'central', 'russia', 'population', 'estimated', 'million', 'resident', 'within', 'city', 'limit', 'million', 'resident', 'urban', 'area', 'million', 'resident', 'metropolitan', 'area', 'city', 'cover', 'area', 'square', 'kilometer', 'sq', 'mi', 'urban', 'area', 'cover', 'square', 'kilometer', 'sq', 'mi', 'metropolitan', 'area', 'cover', 'square', 'kilometer', 'sq', 'mi', 'moscow', 'among', 'world', 'largest', 'city', 'populous', 'city', 'entirely', 'europe', 'largest', 'urban', 'metropolitan', 'area', 'europe', 'largest', 'city', 'land', 'area', 'european', 'documented', 'moscow', 'became', 'capital', 'grand', 'principality', 'moscow', 'led', 'unification', 'russian', 'land', 'century', 'became', 'center', 'unified', 'state', 'following', 'proclamation', 'tsardom', 'russia', 'moscow', 'remained', 'political', 'economic', 'center', 'history', 'reign', 'peter', 'great', 'russian', 'capital', 'moved', 'newly

In [8]:
#Стемминг - определение основ
from nltk.stem import PorterStemmer
porter = PorterStemmer()
 
# используем list comprehension вместо цикла for для стемминга и создания нового списка
# такая запись намного короче
stemmed_p = [porter.stem(s) for s in lemmatized]
print(stemmed_p)

['moscow', 'capit', 'largest', 'citi', 'russia', 'stand', 'moskva', 'river', 'central', 'russia', 'popul', 'estim', 'million', 'resid', 'within', 'citi', 'limit', 'million', 'resid', 'urban', 'area', 'million', 'resid', 'metropolitan', 'area', 'citi', 'cover', 'area', 'squar', 'kilomet', 'sq', 'mi', 'urban', 'area', 'cover', 'squar', 'kilomet', 'sq', 'mi', 'metropolitan', 'area', 'cover', 'squar', 'kilomet', 'sq', 'mi', 'moscow', 'among', 'world', 'largest', 'citi', 'popul', 'citi', 'entir', 'europ', 'largest', 'urban', 'metropolitan', 'area', 'europ', 'largest', 'citi', 'land', 'area', 'european', 'document', 'moscow', 'becam', 'capit', 'grand', 'princip', 'moscow', 'led', 'unif', 'russian', 'land', 'centuri', 'becam', 'center', 'unifi', 'state', 'follow', 'proclam', 'tsardom', 'russia', 'moscow', 'remain', 'polit', 'econom', 'center', 'histori', 'reign', 'peter', 'great', 'russian', 'capit', 'move', 'newli', 'found', 'citi', 'saint', 'petersburg', 'lead', 'declin', 'moscow', 'import'

In [9]:
#Частотная характеристика теста
# из модуля collections импортируем класс Counter
from collections import Counter
 
# применяем класс Counter к словам после лемматизации
# на выходе возвращается словарь { слово : его частота в тексте }
bow_counter = Counter(lemmatized)
# print(bow_counter)
 
# функция most_common() упорядочивает словарь по значению
# посмотрим на первые 10 наиболее частотных слов
print(bow_counter.most_common(10))

[('moscow', 13), ('city', 13), ('area', 7), ('largest', 6), ('center', 6), ('capital', 5), ('world', 5), ('russian', 5), ('russia', 4), ('urban', 4)]


In [11]:
# импортируем класс CountVectorizer из библиотеки Scikit-learn
from sklearn.feature_extraction.text import CountVectorizer
 
# создаём объект этого класса и
# указываем, что хотим перевести слова в нижний регистр, а также
# отфильтровать стоп-слова через stop_words = 'english'
vectorizer = CountVectorizer(analyzer = "word", 
                             lowercase = True, 
                             tokenizer = None, 
                             preprocessor = None, 
                             stop_words = 'english', 
                             max_features = 5000)
bow_cv = vectorizer.fit_transform(sentences)
print(bow_cv.toarray())

tokens = vectorizer.get_feature_names_out()
tokens



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [2 1 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


array(['000', '10', '1147', '13', '1547', '15th', '1712', '19', '1918',
       '1980', '2018', '21', '26', '275', '511', '891', '970',
       'aftermath', 'area', 'billionaires', 'business', 'capital',
       'center', 'centers', 'central', 'century', 'cities', 'city',
       'coldest', 'continent', 'continued', 'covers', 'cultural', 'cup',
       'decline', 'dissolution', 'documented', 'eastern', 'economic',
       'economies', 'entirely', 'establishment', 'estimated', 'europe',
       'european', 'europes', 'experienced', 'features', 'federal',
       'federation', 'fifa', 'financial', 'following', 'founded',
       'governed', 'grand', 'great', 'growth', 'highest', 'history',
       'hong', 'host', 'imperial', 'importance', 'international',
       'kilometers', 'kong', 'land', 'lands', 'largest', 'later',
       'leading', 'led', 'limits', 'majority', 'megacity', 'metropolitan',
       'mi', 'million', 'moscow', 'moskva', 'moved', 'newly',
       'northernmost', 'number', 'olympics'

In [12]:
# вначале создадим индекс предложений (документов)
index_list = []
 
# в цикле пройдемся по элементам матрицы, обозначим их через '_'
# функция enumerate задаст каждому элементу индекс, начиная с 0
for i, _ in enumerate(bow_cv):
 
    # прибавим индекс к слову Sentence 
    index_list.append(f'Sentence_{i}')
 
# теперь можно использовать pd.DataFrame()
bow_cv_df = pd.DataFrame(data = bow_cv.toarray(), 
                         index = index_list, 
                         columns = tokens)
bow_cv_df

000  10  1147  13  1547  15th  1712  19  1918  1980  ...  state  \
Sentence_0     0   0     0   0     0     0     0   0     0     0  ...      0   
Sentence_1     0   0     0   1     0     0     0   1     0     0  ...      0   
Sentence_2     2   1     0   0     0     0     0   0     0     0  ...      0   
Sentence_3     0   0     1   0     0     1     0   0     0     0  ...      1   
Sentence_4     0   0     0   0     1     0     0   0     0     0  ...      0   
Sentence_5     0   0     0   0     0     0     1   0     0     0  ...      0   
Sentence_6     0   0     0   0     0     0     0   0     1     0  ...      0   
Sentence_7     0   0     0   0     0     0     0   0     0     0  ...      0   
Sentence_8     0   0     0   0     0     0     0   0     0     0  ...      0   
Sentence_9     0   0     0   0     0     0     0   0     0     0  ...      0   
Sentence_10    0   0     0   0     0     0     0   0     0     0  ...      0   
Sentence_11    0   0     0   0     0     0     0   0     0     0  ...      0   
Sentence_12    0   0     0   0     0     0     0   0     0     1  ...      0   

             summer  tallest  tied  tsardom  unification  unified  union  \
Sentence_0        0        0     0        0            0        0      0   
Sentence_1        0        0     0        0            0        0      0   
Sentence_2        0        0     0        0            0        0      0   
Sentence_3        0        0     0        0            1        1      0   
Sentence_4        0        0     0        1            0        0      0   
Sentence_5        0        0     0        0            0        0      0   
Sentence_6        0        0     0        0            0        0      0   
Sentence_7        0        0     0        0            0        0      1   
Sentence_8        0        0     0        0            0        0      1   
Sentence_9        0        0     0        0            0        0      0   
Sentence_10       0        0     1        0            0        0      0   
Sentence_11       0        1     0        0            0        0      0   
Sentence_12       1        0     0        0            0        0      0   

             urban  world  
Sentence_0       0      0  
Sentence_1       1      0  
Sentence_2       1      0  
Sentence_3       1      1  
Sentence_4       0      0  
Sentence_5       0      0  
Sentence_6       0      0  
Sentence_7       0      0  
Sentence_8       0      1  
Sentence_9       1      1  
Sentence_10      0      0  
Sentence_11      0      1  
Sentence_12      0      1  

[13 rows x 123 columns]

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
# создаем объект класса TfidfVectorizer
tfIdfVectorizer = TfidfVectorizer(use_idf = True, stop_words= 'english')
 
# сразу рассчитываем TF-IDF слов
tfIdf = tfIdfVectorizer.fit_transform(sentences)
print(tfIdfVectorizer.get_feature_names_out())
df_tfidf = pd.DataFrame(tfIdf.toarray(), columns = tfIdfVectorizer.get_feature_names_out())
print(df_tfidf.T)

['000' '10' '1147' '13' '1547' '15th' '1712' '19' '1918' '1980' '2018'
 '21' '26' '275' '511' '891' '970' 'aftermath' 'area' 'billionaires'
 'business' 'capital' 'center' 'centers' 'central' 'century' 'cities'
 'city' 'coldest' 'continent' 'continued' 'covers' 'cultural' 'cup'
 'decline' 'dissolution' 'documented' 'eastern' 'economic' 'economies'
 'entirely' 'establishment' 'estimated' 'europe' 'european' 'europes'
 'experienced' 'features' 'federal' 'federation' 'fifa' 'financial'
 'following' 'founded' 'governed' 'grand' 'great' 'growth' 'highest'
 'history' 'hong' 'host' 'imperial' 'importance' 'international'
 'kilometers' 'kong' 'land' 'lands' 'largest' 'later' 'leading' 'led'
 'limits' 'majority' 'megacity' 'metropolitan' 'mi' 'million' 'moscow'
 'moskva' 'moved' 'newly' 'northernmost' 'number' 'olympics' 'period'
 'peter' 'petersburg' 'political' 'population' 'populous' 'principality'
 'proclamation' 'reconstituted' 'reign' 'remained' 'residents'
 'revolution' 'river' 'russia' '

In [14]:
mean_weights = np.asarray(tfIdf.mean(axis = 0)).ravel().tolist()
mean_weights

[0.01961323635722591,
 0.009806618178612956,
 0.013713521823015457,
 0.014709348808460889,
 0.027245333641126863,
 0.013713521823015457,
 0.02021338337242547,
 0.014709348808460889,
 0.02727024354684787,
 0.022663467604324916,
 0.022663467604324916,
 0.014709348808460889,
 0.009806618178612956,
 0.009806618178612956,
 0.009806618178612956,
 0.009806618178612956,
 0.009806618178612956,
 0.015602528864083642,
 0.06596804716974357,
 0.028309399625306625,
 0.023808673972977694,
 0.06566722082698406,
 0.06574627648383824,
 0.023808673972977694,
 0.027920701517501305,
 0.013713521823015457,
 0.03137018365102165,
 0.0937879226204869,
 0.015602528864083642,
 0.013713521823015457,
 0.015602528864083642,
 0.02941985453583887,
 0.015602528864083642,
 0.022663467604324916,
 0.02021338337242547,
 0.015602528864083642,
 0.013713521823015457,
 0.015602528864083642,
 0.0369504276467678,
 0.048456368919055935,
 0.013713521823015457,
 0.02727024354684787,
 0.014709348808460889,
 0.037107127701247404,
 0

In [16]:
mean_weights_df = pd.DataFrame({'term': tfIdfVectorizer.get_feature_names_out(), 'mean_weights': mean_weights})
 
# сортируем по убыванию 10 слов с максимальным средним TF-IDF
mean_weights_df.sort_values(by = 'mean_weights', ascending = False).reset_index(drop = True).head(20)


term  mean_weights
0      moscow      0.125651
1     largest      0.097368
2        city      0.093788
3       world      0.077910
4      russia      0.075469
5     russian      0.071700
6        area      0.065968
7      center      0.065746
8     capital      0.065667
9       urban      0.059723
10     soviet      0.055670
11  political      0.051483
12  economies      0.048456
13  following      0.047012
14       host      0.045327
15    million      0.044128
16  residents      0.044128
17      moved      0.040948
18     period      0.038539
19     europe      0.037107